export interface HotelTarget {
  name: string;
  city: string;
  country: string;
}

export const KEMPINSKI_TARGETS: HotelTarget[] = [
  { name: 'Barbaros Reserve Residences', city: 'Bodrum', country: 'Turkey' },
  { name: 'Yanqi Island Pavilion Beijing', city: 'Beijing', country: 'China' },
  { name: 'Bristoria Hotel Erbil', city: 'Erbil', country: 'Iraq' },
  { name: 'Bristoria Hotel Yangzhou', city: 'Yangzhou', country: 'China' },
  { name: 'Kempinski Central Avenue Dubai', city: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Ciragan Palace Kempinski Istanbul', city: 'Istanbul', country: 'Turkey' },
  { name: 'Djibouti Palace Kempinski', city: 'Djibouti', country: 'Djibouti' },
  { name: 'Grand Hotel des Bains Kempinski', city: 'St. Moritz', country: 'Switzerland' },
  { name: 'Grand Hotel Kempinski High Tatras', city: 'Strbske Pleso', country: 'Slovakia' },
  { name: 'Grand Hotel Kempinski Riga', city: 'Riga', country: 'Latvia' },
  { name: 'Grand Kempinski Hotel Shanghai', city: 'Shanghai', country: 'China' },
  { name: 'Gran Hotel Manzana Kempinski La Habana', city: 'Havana', country: 'Cuba' },
  { name: 'Hotel Adlon Kempinski Berlin', city: 'Berlin', country: 'Germany' },
  { name: 'Hotel Adriatic Kempinski', city: 'Opatija', country: 'Croatia' },
  { name: 'Kempinski Hotel Al Othman', city: 'Al Khobar', country: 'Saudi Arabia' },
  { name: 'Kempinski Hotel Aqaba Red Sea', city: 'Aqaba', country: 'Jordan' },
  { name: 'Kempinski Hotel Bahia', city: 'Estepona', country: 'Spain' },
  { name: 'Hotel Baltschug Kempinski Moscow', city: 'Moscow', country: 'Russia' },
  { name: 'Kempinski Hotel Barbaros Bay Bodrum', city: 'Bodrum', country: 'Turkey' },
  { name: 'Kempinski Hotel Brazzaville', city: 'Brazzaville', country: 'Republic of the Congo' },
  { name: 'Kempinski Hotel Cancun', city: 'Cancun', country: 'Mexico' },
  { name: 'Kempinski Hotel Chengdu', city: 'Chengdu', country: 'China' },
  { name: 'Kempinski Hotel Chongqing', city: 'Chongqing', country: 'China' },
  { name: 'Kempinski Hotel Corvinus Budapest', city: 'Budapest', country: 'Hungary' },
  { name: 'Kempinski Hotel Das Tirol', city: 'Jochberg', country: 'Austria' },
  { name: 'Kempinski Gold Coast City Hotel', city: 'Accra', country: 'Ghana' },
  { name: 'Kempinski Hotel Grand Arena Bansko', city: 'Bansko', country: 'Bulgaria' },
  { name: 'Kempinski Hotel Guiyang', city: 'Guiyang', country: 'China' },
  { name: 'Kempinski Hotel Hangzhou', city: 'Hangzhou', country: 'China' },
  { name: 'Hotel Indonesia Kempinski Jakarta', city: 'Jakarta', country: 'Indonesia' },
  { name: 'Kempinski Hotel Ishtar Dead Sea', city: 'Dead Sea', country: 'Jordan' },
  { name: 'Kempinski Hotel Khan Palace Ulaanbaatar', city: 'Ulaanbaatar', country: 'Mongolia' },
  { name: 'Kempinski Hotel San Lawrenz Gozo', city: 'San Lawrenz', country: 'Malta' },
  { name: 'Kempinski Hotel Shenzhen', city: 'Shenzhen', country: 'China' },
  { name: 'Kempinski Hotel Soma Bay', city: 'Soma Bay', country: 'Egypt' },
  { name: 'Kempinski Hotel Suzhou', city: 'Suzhou', country: 'China' },
  { name: 'Kempinski Hotel Taiyuan', city: 'Taiyuan', country: 'China' },
  { name: 'Hotel Taschenbergpalais Kempinski Dresden', city: 'Dresden', country: 'Germany' },
  { name: 'Kempinski Hotel The Dome Belek', city: 'Belek', country: 'Turkey' },
  { name: 'Hotel Vier Jahreszeiten Kempinski Munich', city: 'Munich', country: 'Germany' },
  { name: 'Villa Rosa Kempinski Nairobi', city: 'Nairobi', country: 'Kenya' },
  { name: 'Kempinski Hotel Xiamen', city: 'Xiamen', country: 'China' },
  { name: 'Kempinski Hotel Beijing Yansha Center', city: 'Beijing', country: 'China' },
  { name: 'Kempinski Hotel Berchtesgaden', city: 'Berchtesgaden', country: 'Germany' },
  { name: 'Kempinski Hotel Changsha', city: 'Changsha', country: 'China' },
  { name: 'Kempinski Hotel Fuzhou', city: 'Fuzhou', country: 'China' },
  { name: 'Kempinski Hotel Jinan', city: 'Jinan', country: 'China' },
  { name: 'Kempinski Hotel Muscat', city: 'Muscat', country: 'Oman' },
  { name: 'Kempinski Hotel Nanjing', city: 'Nanjing', country: 'China' },
  { name: 'Kempinski Hotel Yinchuan', city: 'Yinchuan', country: 'China' },
  { name: 'Kempinski Palace Cairo', city: 'Cairo', country: 'Egypt' },
  { name: 'Kempinski Palace Engelberg', city: 'Engelberg', country: 'Switzerland' },
  { name: 'Kempinski Residences Guangzhou', city: 'Guangzhou', country: 'China' },
  { name: 'Kempinski Summerland Hotel & Resort Beirut', city: 'Beirut', country: 'Lebanon' },
  { name: 'Kempinski Hotel Mall of the Emirates Dubai', city: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Marsa Malaz Kempinski The Pearl Doha', city: 'Doha', country: 'Qatar' },
  { name: 'Kempinski Nile Hotel Cairo', city: 'Cairo', country: 'Egypt' },
  { name: 'Olare Mara Kempinski', city: 'Masai Mara', country: 'Kenya' },
  { name: 'Kempinski Palace Portoroz', city: 'Portoroz', country: 'Slovenia' },
  { name: 'Kempinski Hotel & Residences Palm Jumeirah', city: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Kempinski Residences & Suites Doha', city: 'Doha', country: 'Qatar' },
  { name: 'Royal Maxim Palace Kempinski Cairo', city: 'Cairo', country: 'Egypt' },
  { name: 'Kempinski Seychelles Resort', city: 'Mahe', country: 'Seychelles' },
  { name: 'Siam Kempinski Hotel Bangkok', city: 'Bangkok', country: 'Thailand' },
  { name: 'Sindhorn Kempinski Hotel Bangkok', city: 'Bangkok', country: 'Thailand' },
  { name: 'Sunrise Kempinski Hotel Beijing', city: 'Beijing', country: 'China' },
  { name: 'The Apurva Kempinski Bali', city: 'Bali', country: 'Indonesia' },
  { name: 'The Boulevard Hotel Kempinski Dubai', city: 'Dubai', country: 'United Arab Emirates' },
  { name: 'The Capitol Kempinski Hotel Singapore', city: 'Singapore', country: 'Singapore' },
  { name: 'The David Kempinski Tel Aviv', city: 'Tel Aviv', country: 'Israel' },
  { name: 'The One Executive Suites Shanghai', city: 'Shanghai', country: 'China' },
  { name: 'Kempinski Hotel & Resort Sariya Yanbu', city: 'Yanbu', country: 'Saudi Arabia' },
  { name: 'Yanqi Hotel Beijing Managed by Kempinski', city: 'Beijing', country: 'China' },
];
